# Playbook create and written by: Travis Michette
# Contact information: tmichett@redhat.com
# Designed and Written for Fedora
---
- name: Installation of Virt-Manager and Qemu Packages and Configure Networking
  hosts: "{{ variable_host | default('localhost') }}"
  var:
    nic_name: enp0s31f6    # Replace with NIC Name in here or run with "-e nic_name=XXXX" on CLI
  gather_facts: true 
  tasks:

    - name: Install Virtualization Pacakges
      yum:
        name: 
          - virt-manager
          - libvirt
          - qemu
          - libguestfs
          -  bridge-utils
        state: latest 

    - name: Enable Nested Virtualization
      copy:
        content: options kvm_intel nested=1
        dest: /etc/modprobe.d/kvm.conf
        backup: true
      when: "{{ ansible_facts['ansible_processor'] }}" contains 'Intel'

    - name: Enable Nested Virtualization
      copy:
        content: options kvm_amd nested=1
        dest: /etc/modprobe.d/kvm.conf
        backup: true
      when: "{{ ansible_facts['ansible_processor'] }}" contains AMD

    - name: Set and Enable Libvirt Service
      systemd:
        name: libvirtd
        state: started
        enabled: true  

    - name: Create Bridge for Virtual Networking
      shell:  ip link add KVMbr0 type bridge
    
    - name: Attach NIC to Virtual Bridge 
      shell: ip link set {{ nic_name }} master KVMbr0




